import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../styles/Login.module.css";
import React, { useState } from "react";
import axios from "axios";
const LOGIN_URL = "https://reqres.in/api/login";

export default function Login() {
  const [loginState, setLoginState] = useState("none");
  const [loginData, setLoginData] = useState({ email: "", password: "" });
  const router = useRouter();

  const allowAccess = (accessData) => {
    const tokenValue = JSON.stringify(accessData.data.token);
    localStorage.setItem("token", tokenValue);
    router.push("/home");
  };

  const onLoginHandler = async (e) => {
    e.preventDefault();
    setLoginState("loading");
    const data = await axios
      .post(LOGIN_URL, { ...loginData })
      .then((res) => allowAccess(res))
      .catch(() => setLoginState("error"));
    setLoginData({ email: "", password: "" });
  };

  const displayStatus = () => {
    if (loginState === "loading") return <p> Loading... </p>;
    if (loginState === "error")
      return <p className={styles["error"]}> Wrong email or password</p>;
  };

  return (
    <div className={styles["container"]}>
      <Head>
        <title>PokeDex</title>
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
          integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm"
          crossOrigin="anonymous"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles["main"]}>
        <div className={styles["container"]}>
          <form onSubmit={onLoginHandler} className={styles["form"]}>
            <h1 className={styles["title"]}> LOGIN</h1>
            <div className={styles["input-content"]}>
              <i className="fas fa-user"></i>
              <input
                value={loginData.email}
                onChange={(e) =>
                  setLoginData({ ...loginData, email: e.target.value })
                }
                required
                className={styles["input"]}
                type="email"
                placeholder="Email"
              ></input>
            </div>
            <div className={styles["input-content"]}>
              <i className="fas fa-lock"></i>
              <input
                value={loginData.password}
                onChange={(e) =>
                  setLoginData({ ...loginData, password: e.target.value })
                }
                required
                className={styles["input"]}
                type="password"
                placeholder="Password"
              ></input>
            </div>
            {displayStatus()}
            <button className={styles["button"]}>Login</button>
          </form>
        </div>
      </main>
    </div>
  );
}
